[package]
name = "sol_rs_server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
solana-client = "1.18.14"
solana-sdk = "1.18.14"
tokio = { version = "1.45.1", features = ["full"] }